---
- name: Disable default vhost
  file:
    path: /etc/nginx/sites-enabled/default.conf
    state: absent
  notify: reload nginx

- name: Create htpasswd-users
  template:
    dest: /etc/nginx/htpasswd-users
    src: htpasswd-users.j2
    owner: "{{ nginx_vhost_nginx_user }}"
    group: "{{ nginx_vhost_nginx_group }}"
  when: nginx_vhost_basic_auth_users is defined and nginx_vhost_basic_auth_users > 0

- name: Copy virtualhost configurations
  template:
    src: vhost-template.j2
    dest: /etc/nginx/sites-available/{{ nginx_vhost_host }}.conf
    backup: true
  notify: reload nginx

- name: Enable nginx vhost
  file:
    src: /etc/nginx/sites-available/{{ nginx_vhost_host }}.conf
    path: /etc/nginx/sites-enabled/{{ nginx_vhost_host }}.conf
    state: link
  notify: restart nginx

- name: Enable logrotate for vhost
  template:
    src: vhost-logrotate.j2
    dest: "/etc/logrotate.d/nginx-{{ nginx_vhost_host }}"
    owner: root
    group: root
    mode: 0644

- meta: flush_handlers
