---
dependency:
  name: galaxy
driver:
  name: docker
  provider:
    name: virtualbox
platforms:
  - name: instance
    image: ubuntu:18.04
    box: bento/ubuntu-18.04
    memory: "1024mb"
    cpus: 1
    privileged: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
